name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    needs: [build-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y notmuch python3-notmuch python3-venv
          python3 -m venv env
          source ./env/bin/activate
          pip install setuptools pytest dkimpy setuptools_scm wheel twine
          ln -s /usr/lib/python3/dist-packages/notmuch ./env/lib/python*/site-packages
      - name: Build and publish (testpypi)
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.testpypi_token }}
          TWINE_REPOSITORY: testpypi
        run: |
          python setup.py sdist
          twine upload dist/*
